// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXDvkvDcoaGUwgLoeORQPTiubSApf_vQ',
    appId: '1:306701357276:web:88b24f7addb769c13c6419',
    messagingSenderId: '306701357276',
    projectId: 'ecommerce-firebase-f2305',
    authDomain: 'ecommerce-firebase-f2305.firebaseapp.com',
    storageBucket: 'ecommerce-firebase-f2305.firebasestorage.app',
    measurementId: 'G-8E8R36L4K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-EEmgVxrruLxlDQ5qGyISegTWoL-soyk',
    appId: '1:306701357276:android:da2f0c0024f4e3033c6419',
    messagingSenderId: '306701357276',
    projectId: 'ecommerce-firebase-f2305',
    storageBucket: 'ecommerce-firebase-f2305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwkUzRMZQzaeG3tpHd9sLlnyr_XNLMyiQ',
    appId: '1:306701357276:ios:faad66d1509a3cd43c6419',
    messagingSenderId: '306701357276',
    projectId: 'ecommerce-firebase-f2305',
    storageBucket: 'ecommerce-firebase-f2305.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwkUzRMZQzaeG3tpHd9sLlnyr_XNLMyiQ',
    appId: '1:306701357276:ios:faad66d1509a3cd43c6419',
    messagingSenderId: '306701357276',
    projectId: 'ecommerce-firebase-f2305',
    storageBucket: 'ecommerce-firebase-f2305.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfXDvkvDcoaGUwgLoeORQPTiubSApf_vQ',
    appId: '1:306701357276:web:a9158c60c54b6a623c6419',
    messagingSenderId: '306701357276',
    projectId: 'ecommerce-firebase-f2305',
    authDomain: 'ecommerce-firebase-f2305.firebaseapp.com',
    storageBucket: 'ecommerce-firebase-f2305.firebasestorage.app',
    measurementId: 'G-S6E2D6MDSR',
  );
}
